Make osmflat more compact (especially when compressed)
boxdot/osmflat-rs pull request #70
Opened 2022-10-24 14:40 UTC by VeaaC

* Store granularity explicitly instead of pre-multiplied numbers
* Move Ids to separate optional sub-archive
* Reduce bits needed for coordinates from 40 to 32
* Remove unused header information

Comparison:

Comparing:
* Compressed PBF (internal zlib compression)
* Unpacked osmflat with and without optional Ids (only new version has them optional)
* Compression with pzstd level 3
* Compression with shuffly ( https://github.com/VeaaC/shuffly ) + pzstd level 3

Before:

| Dataset  | PBF (zlib) | osmflat w Ids | zstd + osmflat w Ids | shuffly + zstd + osmflat w Ids |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Berlin  | 70M  | 227M  | 94M  | 58M  |
| Europe  | 26G  | 89G  | 41G  | 23G  |
| Planet | 66G  | 223G  | 102G  | 57G  |

After:

| Dataset  | PBF (zlib) | osmflat w Ids | osmflat w/o Ids | zstd + osmflat w Ids | zstd + osmflat w/o Ids | shuffly + zstd + osmflat w Ids | shuffly + zstd + osmflat w/o Ids |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Berlin  | 70M  | 214M  | 176M  | 83M  | 69M  | 53M  | 49M  |
| Europe  | 26G  | 84G  | 68G  | 36G  | 30G  | 20G  | 19G  |
| Planet | 66G  | 208G  | 164G  | 97G  | 76G  | 48G  | 47G  |

Observations:
* More compact in all scenarios.
* Using shuffly is still worth it (Ids have a compression ratio of > factor 20), but a bit less so due to rearranged data, and granularity.
* Shuffly compressed version is smaller than compressed PBF (with and without Ids)
* Most people might want to use a version without ids since it saves disk space
* Ids are almost for free if compressed with shuffly (due to data being sorted by id)

2022-10-24 15:12 UTC, hallahan commented on flatdata/osm.flatdata
> +    lon: i32 : 32;
👍

2022-10-24 15:12 UTC, hallahan commented on osmflatc/src/main.rs
> +        header.set_bbox_bottom((bbox.bottom / (1000000000 / coord_scale) as i64) as i32);
Consistent granularity for everything. 👍

2022-10-25 15:22 UTC, hallahan commented
Such a big difference! I wonder how much better it would be if you reduce integer sizes to 38 bytes instead of 40?

2022-10-26 06:56 UTC, VeaaC commented
Not much / anything at all: Most structures would only be a few bit smaller, and flatdata rounds up to the next byte. It would only help if a structure had 4 references, each saving 2 bits.

2022-10-26 13:20 UTC, boxdot requested changes

2022-10-26 13:20 UTC, boxdot commented on flatdata/osm.flatdata
> -/**
Since the definition has changed, it makes sense also to increase the version of osmflat to 0.2 and release it on crates.io

2022-10-26 14:07 UTC, VeaaC commented on flatdata/osm.flatdata
> -/**
Yeah, we need to bump versions all around after we are done with optimizing things. I would like a bit of time to see if I can think of any other (breaking) improvements, though.

2022-10-26 14:33 UTC, VeaaC commented on flatdata/osm.flatdata
> -/**
Bumped versions and removed debug symbols from release mode.

2022-10-26 14:37 UTC, boxdot approved these changes

2022-10-26 15:07 UTC, merged

2022-10-26 16:25 UTC, hallahan commented
How do you do your size benchmarking? Is there a script somewhere?

2022-10-26 18:10 UTC, boxdot commented
> How do you do your size benchmarking? Is there a script somewhere?

+1 for documenting the command lines which produced the above numbers